export const identityRoutes = {
  login: '/auth/login',
  logout: '/auth/logout',
  me: '/auth/me',
  password: '/auth/password',
  teachers: '/teachers',
  teacherReset: '/teachers/:teacherId/reset-password',
  teacherDeactivate: '/teachers/:teacherId/deactivate',
  teacherReactivate: '/teachers/:teacherId/reactivate',
  classrooms: '/classrooms',
  classroom: '/classrooms/:classroomId',
  classroomTeachers: '/classrooms/:classroomId/teachers',
  classroomDeactivate: '/classrooms/:classroomId/deactivate',
  subjectOptions: '/subjects',
  classroomStudents: '/classrooms/:classroomId/students',
  classroomStudent: '/classrooms/:classroomId/students/:studentId',
  classroomCredentials: '/classrooms/:classroomId/credentials',
  studentReset: '/students/:studentId/reset-password',
  studentDeactivate: '/students/:studentId/deactivate',
  studentReactivate: '/students/:studentId/reactivate',
  students: '/students',
} as const
