export const identityRoutes = {
  login: '/auth/login',
  logout: '/auth/logout',
  me: '/auth/me',
  password: '/auth/password',
  teachers: '/teachers',
  teacherReset: '/teachers/:id/reset-password',
  teacherDeactivate: '/teachers/:id/deactivate',
  teacherReactivate: '/teachers/:id/reactivate',
  classrooms: '/classrooms',
  classroom: '/classrooms/:id',
  classroomTeachers: '/classrooms/:id/teachers',
  classroomDeactivate: '/classrooms/:id/deactivate',
  classroomStudents: '/classrooms/:id/students',
  classroomStudent: '/classrooms/:id/students/:studentId',
  classroomCredentials: '/classrooms/:id/credentials',
  studentReset: '/students/:id/reset-password',
  studentDeactivate: '/students/:id/deactivate',
  studentReactivate: '/students/:id/reactivate',
} as const
