export const identityRoutes = {
  login: '/auth/login',
  logout: '/auth/logout',
  me: '/auth/me',
  password: '/auth/password',
  teachers: '/teachers',
  teacherReset: '/teachers/:teacherId/reset-password',
  teacherDeactivate: '/teachers/:teacherId/deactivate',
  teacherReactivate: '/teachers/:teacherId/reactivate',
  classrooms: '/classrooms',
  classroom: '/classrooms/:classroomId',
  classroomTeachers: '/classrooms/:classroomId/teachers',
  classroomDeactivate: '/classrooms/:classroomId/deactivate',
  subjectOptions: '/subjects',
} as const
