import type { Question, QuestionContent } from '@/modules/content/domain/Question'

export interface QuestionRepository {
  listByTopic(topicId: string): Promise<Question[]>
  /** `id` is generated by the client once per form, so a resend never duplicates. */
  create(topicId: string, id: string, content: QuestionContent): Promise<Question>
  update(id: string, version: number, content: QuestionContent): Promise<Question>
  deactivate(id: string): Promise<Question>
  reactivate(id: string): Promise<Question>
}
